services:
    site_django_todo:
      build: .
      container_name: django_todo
      read_only: true
      tmpfs:
        - /tmp
        - /run
      ports:
        - "8000:8000"

      volumes:
        - ./data:/app/data:rw
        - ./static:/app/static:ro


      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 96M
      restart: always
