# Generated by Django 5.2.8 on 2025-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
